require('settings')
require('lazy-plugins')
require('plugins.catppuccin')
require('plugins.lualine')
require('plugins.neo-tree')
--require('plugins.bufferline')
require('plugins.treesitter')
require('plugins.mason')
require('plugins.mason-lsp-config')
require('plugins.lspconfig')
require('plugins.auto-save')
require('plugins.notify')
require('plugins.telescope')

require('plugins.toggleterm')
require('keymaps')
require('plugins.coc')
require('plugins.coc-notify-int')
